name: Python application tests

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
       
        mkdir -p reports/flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --format=html --htmldir=reports/flake8 || true

    - name: Test with pytest
      run: |
       
        mkdir -p reports/pytest
        xvfb-run pytest --html=reports/pytest/report.html --self-contained-html || true

    - name: Upload Analysis Reports
      uses: actions/upload-artifact@v4
      with:
        name: analysis-reports
        path: reports/